"""PlayStealth GitHub Issue Reporter - Auto-creates issues for failures."""
import os
import hashlib
import httpx
from typing import Optional, Dict, Set
from datetime import datetime, timezone


class GitHubIssueReporter:
    """Erstellt GitHub Issues bei Fehlern mit Deduplication."""
    
    def __init__(self):
        self._enabled = bool(os.getenv("GITHUB_APP_ID") and os.getenv("GITHUB_APP_PRIVATE_KEY"))
        self.app_id = os.getenv("GITHUB_APP_ID")
        self._private_key = os.getenv("GITHUB_APP_PRIVATE_KEY")
        self.installation_id = os.getenv("GITHUB_INSTALLATION_ID")
        self.repo_owner = os.getenv("GITHUB_REPO_OWNER", "your-org")
        self.repo_name = os.getenv("GITHUB_REPO_NAME", "playstealth")
        self._issue_hashes: Set[str] = set()
        self._token_cache: Optional[str] = None
        self._token_expires: Optional[datetime] = None

    async def _get_installation_token(self) -> Optional[str]:
        """Holt JWT Token für GitHub App Installation."""
        if self._token_cache and self._token_expires and datetime.now(timezone.utc) < self._token_expires:
            return self._token_cache
        
        try:
            import jwt
            now = datetime.now(timezone.utc)
            payload = {
                "iat": int(now.timestamp()),
                "exp": int((now.timestamp()) + 600),
                "iss": self.app_id
            }
            app_jwt = jwt.encode(payload, self._private_key, algorithm="RS256")
            
            headers = {"Authorization": f"Bearer {app_jwt}", "Accept": "application/vnd.github.v3+json"}
            url = f"https://api.github.com/app/installations/{self.installation_id}/access_tokens"
            
            async with httpx.AsyncClient(timeout=10) as client:
                res = await client.post(url, headers=headers)
                if res.status_code == 201:
                    data = res.json()
                    self._token_cache = data["token"]
                    # Set expiration to 8 minutes from now (valid range)
                    from datetime import timedelta
                    self._token_expires = now + timedelta(minutes=8)
                    return self._token_cache
        except Exception as e:
            print(f"⚠️ GitHub token fetch failed: {e}")
        return None

    def _dedup_hash(self, module_name: str, error_msg: str) -> str:
        """Generiert dedup hash für issue."""
        return hashlib.sha256(f"{module_name}:{error_msg}".encode()).hexdigest()[:12]

    async def create_issue(
        self,
        module_name: str,
        error_msg: str,
        traceback_str: str,
        severity: str = "high",
        labels: Optional[list] = None
    ) -> Optional[str]:
        """Erstellt GitHub Issue wenn noch nicht existent."""
        if not self._enabled:
            return None
        
        h = self._dedup_hash(module_name, error_msg)
        if h in self._issue_hashes:
            return None
        self._issue_hashes.add(h)
        
        token = await self._get_installation_token()
        if not token:
            return None
        
        labels = labels or ["bug", "auto-generated", f"severity:{severity}"]
        title = f"🚨 {severity.upper()}: {module_name} failure"
        body = f"""## Error Details

**Module:** `{module_name}`
**Severity:** {severity}
**Timestamp:** {datetime.now(timezone.utc).isoformat()}

### Error Message
```
{error_msg[:2000]}
```

### Traceback
```
{traceback_str[:3000]}
```

---
*Auto-generated by PlayStealth Issue Reporter*
"""
        
        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github.v3+json"
        }
        
        try:
            async with httpx.AsyncClient(timeout=15) as client:
                url = f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/issues"
                res = await client.post(url, json={
                    "title": title,
                    "body": body,
                    "labels": labels
                }, headers=headers)
                
                if res.status_code == 201:
                    return res.json()["html_url"]
        except Exception as e:
            print(f"⚠️ GitHub issue creation failed: {e}")
        
        return None
